<?php
date_default_timezone_set( 'Asia/Hong_Kong' );
define( 'DOCUMENT_ROOT', '/usr/local/banyue/' );
define( 'FACEBOOK_SDK_V4_SRC_DIR', DOCUMENT_ROOT.'api/facebook-php-sdk-v4/src/Facebook' );
define( 'WORLDHERO_SECRET', '%$#&*WOrlD-+)5<HeRo?]|~2015{[}' );
define( 'FB_APP_ID',     '1064006016944757' );
define( 'FB_APP_SECRET', 'ade39c2b13886d30b8b0c674a2dfec99' );
define( 'DB_USER_NAME',  'root' );
define( 'DB_PASSWD',     'c5c94c3eb831b8ef7b3b392bf9d29638' );

define( 'MAX_HID', 9999 );
define( 'MIN_HID', 1001 );

define( 'MYSQL_GET',    1 );
define( 'MYSQL_INSERT', 2 );
define( 'MYSQL_UPDATE', 3 );
define( 'MYSQL_DELETE', 4 );
define( 'MYSQLI_GET',   5 );

define( 'MYSQL_SQLGET',    1 );
define( 'MYSQL_SQLINSERT', 2 );
define( 'MYSQL_SQLUPDATE', 3 );
define( 'MYSQL_SQLDELETE', 4 );

define( 'PINZHI_LV'		, 'lv' );
define( 'PINZHI_LAN'	, 'lan' );
define( 'PINZHI_ZI'		, 'zi' );
define( 'PINZHI_JIN'	, 'jin' );

/* 背包物品ID */
define( 'T_MEDICINE', 10001 );
define( 'M_MEDICINE', 10002 );
define( 'B_MEDICINE', 10003 );
define( 'S_MEDICINE', 10004 );
define( 'SHOW_DIAMOND', 10005 );
define( 'SHOW_COIN',  10006 );
//升级品质材料-突破胶囊
define( 'JIAOLANG_WUGONG_LV' , 20011 );
define( 'JIAOLANG_WUGONG_LAN', 20012 );
define( 'JIAOLANG_WUGONG_ZI' , 20013 );
define( 'JIAOLANG_WUGONG_JIN', 20014 );
define( 'JIAOLANG_MOGONG_LV' , 20021 );
define( 'JIAOLANG_MOGONG_LAN', 20022 );
define( 'JIAOLANG_MOGONG_ZI' , 20023 );
define( 'JIAOLANG_MOGONG_JIN', 20024 );
define( 'JIAOLANG_HUJIA_LV' , 20031 );
define( 'JIAOLANG_HUJIA_LAN', 20032 );
define( 'JIAOLANG_HUJIA_ZI' , 20033 );
define( 'JIAOLANG_HUJIA_JIN', 20034 );
define( 'JIAOLANG_MOKANG_LV' , 20041 );
define( 'JIAOLANG_MOKANG_LAN', 20042 );
define( 'JIAOLANG_MOKANG_ZI' , 20043 );
define( 'JIAOLANG_MOKANG_JIN', 20044 );
define( 'JIAOLANG_CROSS_LV' , 20051 );
define( 'JIAOLANG_CROSS_LAN', 20052 );
define( 'JIAOLANG_CROSS_ZI' , 20053 );
define( 'JIAOLANG_CROSS_JIN', 20054 );
define( 'JIAOLANG_BLOOD_LV' , 20061 );
define( 'JIAOLANG_BLOOD_LAN', 20062 );
define( 'JIAOLANG_BLOOD_ZI' , 20063 );
define( 'JIAOLANG_BLOOD_JIN', 20064 );

//升级奥义-奥义卷轴 物品id
define( 'AOYI_BLOOD_TYPENAME'	, 'blood_aoyi' );
define( 'AOYI_ATTACK_TYPENAME'	, 'attack_aoyi' );
define( 'AOYI_HUJIA_TYPENAME'	, 'parmor_aoyi' );
define( 'AOYI_MOKANG_TYPENAME'	, 'marmor_aoyi' );
define( 'AOYI_SPEED_TYPENAME'	, 'cross_aoyi' );
$AOYI_JUANZHOU_CONFIG = array();
$AOYI_JUANZHOU_CONFIG[AOYI_BLOOD_TYPENAME] = array();
$AOYI_JUANZHOU_CONFIG[AOYI_BLOOD_TYPENAME][PINZHI_LV] 	= 30011;
$AOYI_JUANZHOU_CONFIG[AOYI_BLOOD_TYPENAME][PINZHI_LAN] 	= 30012;
$AOYI_JUANZHOU_CONFIG[AOYI_BLOOD_TYPENAME][PINZHI_ZI] 	= 30013;
$AOYI_JUANZHOU_CONFIG[AOYI_BLOOD_TYPENAME][PINZHI_JIN] 	= 30014;
$AOYI_JUANZHOU_CONFIG[AOYI_ATTACK_TYPENAME] = array();
$AOYI_JUANZHOU_CONFIG[AOYI_ATTACK_TYPENAME][PINZHI_LV] 	= 30021;
$AOYI_JUANZHOU_CONFIG[AOYI_ATTACK_TYPENAME][PINZHI_LAN] = 30022;
$AOYI_JUANZHOU_CONFIG[AOYI_ATTACK_TYPENAME][PINZHI_ZI] 	= 30023;
$AOYI_JUANZHOU_CONFIG[AOYI_ATTACK_TYPENAME][PINZHI_JIN] = 30024;
$AOYI_JUANZHOU_CONFIG[AOYI_HUJIA_TYPENAME] = array();
$AOYI_JUANZHOU_CONFIG[AOYI_HUJIA_TYPENAME][PINZHI_LV] 	= 30031;
$AOYI_JUANZHOU_CONFIG[AOYI_HUJIA_TYPENAME][PINZHI_LAN] 	= 30032;
$AOYI_JUANZHOU_CONFIG[AOYI_HUJIA_TYPENAME][PINZHI_ZI] 	= 30033;
$AOYI_JUANZHOU_CONFIG[AOYI_HUJIA_TYPENAME][PINZHI_JIN] 	= 30034;
$AOYI_JUANZHOU_CONFIG[AOYI_MOKANG_TYPENAME] = array();
$AOYI_JUANZHOU_CONFIG[AOYI_MOKANG_TYPENAME][PINZHI_LV] 	= 30041;
$AOYI_JUANZHOU_CONFIG[AOYI_MOKANG_TYPENAME][PINZHI_LAN] = 30042;
$AOYI_JUANZHOU_CONFIG[AOYI_MOKANG_TYPENAME][PINZHI_ZI] 	= 30043;
$AOYI_JUANZHOU_CONFIG[AOYI_MOKANG_TYPENAME][PINZHI_JIN] = 30044;
$AOYI_JUANZHOU_CONFIG[AOYI_SPEED_TYPENAME] = array();
$AOYI_JUANZHOU_CONFIG[AOYI_SPEED_TYPENAME][PINZHI_LV] 	= 30051;
$AOYI_JUANZHOU_CONFIG[AOYI_SPEED_TYPENAME][PINZHI_LAN] 	= 30052;
$AOYI_JUANZHOU_CONFIG[AOYI_SPEED_TYPENAME][PINZHI_ZI] 	= 30053;
$AOYI_JUANZHOU_CONFIG[AOYI_SPEED_TYPENAME][PINZHI_JIN] 	= 30054;


require_once( DOCUMENT_ROOT.'interface/loadClass.php' );
require_once( DOCUMENT_ROOT.'interface/Quality.php' );
require_once( DOCUMENT_ROOT.'interface/Hero.php' );
require_once( DOCUMENT_ROOT.'inc/hero.inc.php' );
require_once( DOCUMENT_ROOT.'inc/quality.inc.php' );
require_once( DOCUMENT_ROOT.'inc/error.inc.php' );
require_once( DOCUMENT_ROOT.'inc/skill.inc.php' );
require_once( DOCUMENT_ROOT.'inc/heroTogether.inc.php' );
require_once( DOCUMENT_ROOT.'inc/task.inc.php' );
?>